"""password column renamed to hashed_password in admin model

Revision ID: 4e6ad7cb8ce7
Revises: 911bd8a06f33
Create Date: 2025-02-11 20:49:11.701334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4e6ad7cb8ce7'
down_revision: Union[str, None] = '911bd8a06f33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('hashed_password', sa.String(length=60), nullable=False))
    op.drop_column('admins', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('password', mysql.VARCHAR(length=60), nullable=False))
    op.drop_column('admins', 'hashed_password')
    # ### end Alembic commands ###
